### ISSUE TITLE
Consequences of changes in SpatialReference

### ISSUE THREAD

**Issue by niniemann** [sempr-tk/sempr#13]
Imagine the following structure of entities: A chain of affine transformations and a few geometries linked to some of the frames:
```
frames     | (root) <-- (foo) <-- (bar) <-- (baz)
geometries |                       ^--- (g1)   ^--- (g2)
```
Now, I'll modify the SpatialReference "foo", and change its transformation to "root".
```
foo->changed();
```
What happens now? Although "bar" and "baz" didn't change directly, they describe a different (global) pose now. So, they `->changed();`, right? And what about the geometries? Their number of points and relative (internal) structure is still the same, but in the global frame they are different. So, they... `->changed();`?

*Context: I'm currently working on a spatial index and need to update the entries for g1 and g2 in case foo changes. Which events do I need to look out for?*

I guess I'll do it like this: No events, no `changed()` for children or geometries. But a way to check which frames are effected, a method like `bool SpatialReference::isChildOf(SpatialReference::Ptr) const`.

However, this could be something to think about a bit longer. Feel free to comment & criticise.

**Comment by Kynneb** [comment]
I don't think bar and baz should be considered as changed - that's the whole concept of having transformation chains. Of course for the SpatialIndex as a cache their coordinates in the root frame have to be recalculated, but this information is already given by foo's changed event as you hinted on in your proposed solution.

For sempr I would not change anything, but the spatial index should have a possibility to check up on all child frames of a changed geometric frame.

**Comment by niniemann** [comment]
> that's the whole concept of having transformation chains

Good point. I agree, and ended up implementing a
```c++
bool SpatialReference::isChildOf(SpatialReference::Ptr other) const;
```
in 6741dc62a68a01ad5d541b9d8d23b2cd2c1f013c.
