### ISSUE TITLE
Experimental: Compile-time-inheritance-traversal

### ISSUE THREAD

**Issue by niniemann** [sempr-tk/sempr#16]
Get rid of preprocessor macros. Use this. Maybe. See [experimental-template-magic](https://github.com/sempr-tk/sempr/blob/experimental-template-magic/include/sempr/utility/Wrapper.hpp) for an extensive description. :wink:

**Comment by Kynneb** [comment]
I will have a look into that the next days :D

**Comment by niniemann** [comment]
I've used parts of this to update the EntityEvent-class. See #21. This didn't get rid of all preprocessor stuff, but it did make the interface nicer, though, I think.
