### ISSUE TITLE
Split tests over multiple files

### ISSUE THREAD

**Issue by Kynneb** [sempr-tk/sempr#22]
As the readabilty of the unit test file decreases with every additional test I propose to distribute them over mutiple files. 

If you agree, I would wait for the latest PR to be merged and then just do it.

**Comment by niniemann** [comment]
I totally agree, please go ahead! 
The latest PR introduces only very minor changes to the tests -- I think it's merely a small change in the include order. So... no need to wait for the PR to be merged. But I won't stop you from reviewing the PR so it can be merged soon, either. :wink:
