### ISSUE TITLE
RDFDocument needed?

### ISSUE THREAD

**Issue by ctieben** [sempr-tk/sempr#43]
Hi,

I'm wondering if the RDFDocument is really needed to exist as separate entity in sempr.

Its mostly a RDFEntity with a spacial source for the triples. All the tripel from the file will be stored locally after the construction.

So I dont see any benefits to store the path to a local file as additional information in the database.

Best regards
ctieben

**Comment by niniemann** [comment]
I wanted to distinguish between rdf data which is provided implicitly from other data sources from triples the user loaded from an external file to bootstrap the system with some basic information. Additionally storing the name of the file that was loaded allows the user to check if the file changed and reload the entity. Also, the RDFDocument provides a method to parse files of different formats.

**Comment by niniemann** [comment]
So I'd say: Yes, it is needed. :wink:
