### ISSUE TITLE
Performance of Database transactions

### ISSUE THREAD

**Issue by Kynneb** [sempr-tk/sempr#6]
At the moment single database transactions are executed for every entity creation or update which might be a performance drag when testing >= 1000 insertions in a row in sqlite. 

In the branch research-database-performance I experiment with storing insertion actions in a buffer array in the update-module and let it do the transactions in bulk when specifically called to do so.

Current tests suggest massive performance boosts when doing such transactions in bulk, so strategies when to do persistence and db updates might be interesting.

**Comment by niniemann** [comment]
I think in GitLab we would create a WIP-merge-request for that, right? Is that a good practise here, too?

**Comment by Kynneb** [comment]
I think so.
